/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    filters: Filter;
    'filter-options': FilterOption;
    products: Product;
    categories: Category;
    'hero-slider': HeroSlider;
    'category-bar': CategoryBar;
    brands: Brand;
    'about-us': AboutUs;
    services: Service;
    'contact-info': ContactInfo;
    'contact-page': ContactPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    filters: FiltersSelect<false> | FiltersSelect<true>;
    'filter-options': FilterOptionsSelect<false> | FilterOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'hero-slider': HeroSliderSelect<false> | HeroSliderSelect<true>;
    'category-bar': CategoryBarSelect<false> | CategoryBarSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ka' | 'en') | ('ka' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'ka' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filters".
 */
export interface Filter {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options".
 */
export interface FilterOption {
  id: number;
  value: string;
  group: number | Filter;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * მონიშნეთ, თუ გსურთ გამოჩნდეს მთავარ სლაიდერში
   */
  isPopular?: boolean | null;
  slug: string;
  description?: string | null;
  specifications?: string | null;
  filter_values?:
    | {
        filter_group: number | Filter;
        value_rel: number | FilterOption;
        id?: string | null;
      }[]
    | null;
  price?: number | null;
  discountPrice?: number | null;
  stock?: ('in-stock' | 'out-of-stock') | null;
  category: number | Category;
  /**
   * პროდუქტი ამ კატეგორიებშიც გამოჩნდება
   */
  additionalCategories?: (number | Category)[] | null;
  brand?: (number | null) | Brand;
  mainImage: number | Media;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  parent?: (number | null) | Category;
  description?: string | null;
  /**
   * აირჩიეთ ფილტრის ჯგუფები (მაგ: რეზოლუცია), რომლებიც ამ კატეგორიაში უნდა გამოჩნდეს
   */
  assignedFilters?: (number | Filter)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slider".
 */
export interface HeroSlider {
  id: number;
  /**
   * მხოლოდ Admin პანელში გამოჩნდება
   */
  title: string;
  /**
   * ღილაკი 1 - ტექსტი (მაგ: "ყველა პროდუქტი")
   */
  buttonAllProducts?: string | null;
  /**
   * ღილაკი 2 - ტექსტი (მაგ: "ჩვენი სერვისები")
   */
  buttonOurServices?: string | null;
  slides?:
    | {
        title: string;
        description: string;
        image: number | Media;
        /**
         * ღილაკი 1 - ლინკი (მაგ: /ka/products)
         */
        link1: string;
        /**
         * ღილაკი 2 - ლინკი (მაგ: /ka/about-us)
         */
        link2: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-bar".
 */
export interface CategoryBar {
  id: number;
  /**
   * მხოლოდ Admin პანელში გამოჩნდება
   */
  title: string;
  /**
   * პირველი ღილაკის ტექსტი (მაგ: "ყველა" / "All Shop")
   */
  allShopLabel?: string | null;
  items?:
    | {
        category: number | Category;
        /**
         * ბარათის ფონის სურათი
         */
        backgroundImage: number | Media;
        /**
         * პატარა ხატულა (SVG/PNG, თეთრი ფონზე)
         */
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: number;
  /**
   * მხოლოდ Admin პანელში გამოჩნდება (მაგ: "About Us - კა")
   */
  title: string;
  hero: {
    titleBlue: string;
    titleBlack: string;
    story: string;
    image: number | Media;
  };
  priority?: {
    title?: string | null;
    sub?: string | null;
    analysis?: string | null;
  };
  directions?: {
    title?: string | null;
    items?:
      | {
          title?: string | null;
          image: number | Media;
          /**
           * გადამისამართების URL (მაგ: /ka/services#cameras)
           */
          link?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  support?: {
    badge?: string | null;
    title?: string | null;
    text1?: string | null;
    text2?: string | null;
  };
  whyUs?: {
    badge?: string | null;
    title?: string | null;
    items?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * მხოლოდ Admin პანელში გამოჩნდება (მაგ: "Services - KA")
   */
  title: string;
  items: {
    title: string;
    description: string;
    brands?:
      | {
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    features?:
      | {
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  cta?: {
    title?: string | null;
    text?: string | null;
  };
  header?: {
    badge?: string | null;
    heading?: string | null;
    sub?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  /**
   * მხოლოდ Admin პანელში გამოჩნდება
   */
  title: string;
  infoTitle?: string | null;
  phone?: string | null;
  email?: string | null;
  socials?:
    | {
        platformName: string;
        icon: 'facebook' | 'instagram' | 'linkedin' | 'twitter' | 'youtube' | 'globe';
        url: string;
        id?: string | null;
      }[]
    | null;
  address?: string | null;
  /**
   * Google Maps embed src URL
   */
  mapEmbedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * მხოლოდ Admin პანელში გამოჩნდება
   */
  title: string;
  /**
   * Hero სათაური (საიტზე გამოჩნდება)
   */
  contactPageTitle?: string | null;
  subtitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'filters';
        value: number | Filter;
      } | null)
    | ({
        relationTo: 'filter-options';
        value: number | FilterOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'hero-slider';
        value: number | HeroSlider;
      } | null)
    | ({
        relationTo: 'category-bar';
        value: number | CategoryBar;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'about-us';
        value: number | AboutUs;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'contact-info';
        value: number | ContactInfo;
      } | null)
    | ({
        relationTo: 'contact-page';
        value: number | ContactPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filters_select".
 */
export interface FiltersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "filter-options_select".
 */
export interface FilterOptionsSelect<T extends boolean = true> {
  value?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  isPopular?: T;
  slug?: T;
  description?: T;
  specifications?: T;
  filter_values?:
    | T
    | {
        filter_group?: T;
        value_rel?: T;
        id?: T;
      };
  price?: T;
  discountPrice?: T;
  stock?: T;
  category?: T;
  additionalCategories?: T;
  brand?: T;
  mainImage?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  description?: T;
  assignedFilters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slider_select".
 */
export interface HeroSliderSelect<T extends boolean = true> {
  title?: T;
  buttonAllProducts?: T;
  buttonOurServices?: T;
  slides?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link1?: T;
        link2?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-bar_select".
 */
export interface CategoryBarSelect<T extends boolean = true> {
  title?: T;
  allShopLabel?: T;
  items?:
    | T
    | {
        category?: T;
        backgroundImage?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        titleBlue?: T;
        titleBlack?: T;
        story?: T;
        image?: T;
      };
  priority?:
    | T
    | {
        title?: T;
        sub?: T;
        analysis?: T;
      };
  directions?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              title?: T;
              image?: T;
              link?: T;
              id?: T;
            };
      };
  support?:
    | T
    | {
        badge?: T;
        title?: T;
        text1?: T;
        text2?: T;
      };
  whyUs?:
    | T
    | {
        badge?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        brands?:
          | T
          | {
              name?: T;
              id?: T;
            };
        features?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
      };
  header?:
    | T
    | {
        badge?: T;
        heading?: T;
        sub?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  title?: T;
  infoTitle?: T;
  phone?: T;
  email?: T;
  socials?:
    | T
    | {
        platformName?: T;
        icon?: T;
        url?: T;
        id?: T;
      };
  address?: T;
  mapEmbedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  title?: T;
  contactPageTitle?: T;
  subtitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}